name: TranslateLocal
options:
  bundleIdPrefix: oceania1984.InIndiana.AWT
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  minimumXcodeGenVersion: "2.35.0"
  generateEmptyDirectories: false

settings:
  base:
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    SWIFT_VERSION: "5.0"
    DEVELOPMENT_TEAM: ""

targets:
  TranslateLocal:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: iOS/TranslateLocal
        excludes:
          - "**/.DS_Store"
          - "**/Info.plist"
          - "Resources/**"
    resources:
      - path: TranslateLocal/Assets.xcassets
    settings:
      base:
        INFOPLIST_FILE: iOS/TranslateLocal/Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: oceania1984.InIndiana.AWT.TranslateLocal
        CODE_SIGN_ENTITLEMENTS: TranslateLocal/TranslateLocal.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        GENERATE_INFOPLIST_FILE: NO
    entitlements:
      path: TranslateLocal/TranslateLocal.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.translatelocal.shared
        # Camera and media permissions (handled via Info.plist privacy descriptions)
        # No additional entitlements needed for camera/photo access
    dependencies:
      - target: ShareExtension
        embed: true
        codeSign: true
        copyPhase:
          destination: plugins
      - target: ActionExtension
        embed: true
        codeSign: true
        copyPhase:
          destination: plugins

  ShareExtension:
    type: app-extension
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: iOS/ShareExtension
        excludes:
          - "**/.DS_Store"
          - "**/Info.plist"
          - "*.entitlements"
    settings:
      base:
        INFOPLIST_FILE: iOS/ShareExtension/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: oceania1984.InIndiana.AWT.TranslateLocal.ShareExtension
        CODE_SIGN_ENTITLEMENTS: iOS/ShareExtension/ShareExtension.entitlements
        SKIP_INSTALL: YES
        GENERATE_INFOPLIST_FILE: NO
    entitlements:
      path: iOS/ShareExtension/ShareExtension.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.translatelocal.shared

  ActionExtension:
    type: app-extension
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: iOS/ActionExtension
        excludes:
          - "**/.DS_Store"
          - "**/Info.plist"
          - "*.entitlements"
    settings:
      base:
        INFOPLIST_FILE: iOS/ActionExtension/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: oceania1984.InIndiana.AWT.TranslateLocal.ActionExtension
        CODE_SIGN_ENTITLEMENTS: iOS/ActionExtension/ActionExtension.entitlements
        SKIP_INSTALL: YES
        GENERATE_INFOPLIST_FILE: NO
    entitlements:
      path: iOS/ActionExtension/ActionExtension.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.translatelocal.shared

schemes:
  TranslateLocal:
    build:
      targets:
        TranslateLocal: all
        ShareExtension: all
        ActionExtension: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
